### ISSUE TITLE
Lintly doesnt work in Windows

### ISSUE THREAD

**Issue by rasjani** [grantmcconnaughey/Lintly#12]
`sh` module currently being used throws  ImportError if lintly is being executed in windows:

```
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\hostedtoolcache\windows\Python\2.7.14\x64\Scripts\lintly.exe\__main__.py", line 5, in <module>
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\lintly\cli.py", line 8, in <module>
    from .ci import find_ci_provider
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\lintly\ci.py", line 5, in <module>
    from . import git
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\lintly\git.py", line 1, in <module>
    import sh
  File "c:\hostedtoolcache\windows\python\2.7.14\x64\lib\site-packages\sh.py", line 36, in <module>
    support." % __version__)
ImportError: sh 1.12.14 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.
```

**Comment by rasjani** [comment]
Also, lintly/projects.py uses hardcoded path separator instead of os.sep
